name: cubiplugin
description: Le Plugin Principal de la Garderie
main: net.ddns.lagarderie.cubiplugin.RacingPlugin
version: 0.0.1
api-version: '1.18'

commands:
  game:
    description: Paramétrage de la partie
  checkpoint:
    description: Paramétrage des checkpoints d'une course
  children:
    description: Gestion des successeurs d'un checkpoint
  track:
    description: Paramétrage d'une course